/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import MainClasses.Customer;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Staff extends javax.swing.JFrame {

    Statement statement;
    ResultSet result;
    ResultSet result2;
    String pattren;
    PreparedStatement prSt;

    DefaultTableModel Allcustemers;

    public Staff() {
        initComponents();
        setEnabled();
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();

        Allcustemers = new DefaultTableModel();
        Allcustemers = (DefaultTableModel) Table1.getModel();

        getAllcustemrs();

    }

    public void getAllcustemrs() {
        try {
            ArrayList<Customer> customers = dbhandler.getAllStudents();
            Allcustemers.setRowCount(0);
            for (Customer cu : customers) {
                Allcustemers.addRow(new String[]{cu.getFullname(), cu.getId(), cu.getRoomNo(), cu.getRoomType(), cu.getCheck_in(), cu.getCheck_out(), cu.getRezerType()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void setEnabled() {
        name1.setEnabled(false);

        IDd.setEnabled(false);

        roomNo.setEnabled(false);

        roomtype1.setEnabled(false);

        check_in.setEnabled(false);
        check_out.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        roomno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        checkout = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        IDd = new javax.swing.JTextField();
        roomNo = new javax.swing.JTextField();
        check_in = new com.toedter.calendar.JDateChooser();
        check_out = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        roomtype1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(77, 134, 156));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(940, 892));

        jPanel3.setBackground(new java.awt.Color(211, 224, 234));
        jPanel3.setPreferredSize(new java.awt.Dimension(940, 508));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 102, 120));
        jLabel3.setText("Booking");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 102, 120));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 102, 120));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 102, 120));
        jLabel5.setText("Room No");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 102, 120));
        jLabel6.setText("Check-in");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 102, 120));
        jLabel8.setText("Check-out");

        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single    => 100", "Double   => 200", "Triple   => 300",
            "Family   => 400", "Suit     => 500" }));

jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
jLabel9.setForeground(new java.awt.Color(39, 102, 120));
jLabel9.setText("Room Type");

jButton3.setBackground(new java.awt.Color(39, 102, 120));
jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
jButton3.setForeground(new java.awt.Color(153, 255, 255));
jButton3.setText("Add custemer");
jButton3.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
    }
    });

    jButton4.setBackground(new java.awt.Color(39, 102, 120));
    jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jButton4.setForeground(new java.awt.Color(153, 255, 255));
    jButton4.setText("Back To Home");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jPanel5.setBackground(new java.awt.Color(77, 134, 156));

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 374, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 531, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(56, 56, 56)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roomno, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(36, 36, 36)
                            .addComponent(checkout, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addGap(62, 62, 62)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(id)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9)
                    .addGap(18, 18, 18)
                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel3))
            .addContainerGap(136, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jLabel3)
            .addGap(62, 62, 62)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addGap(37, 37, 37)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(roomno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(checkout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("Booking", jPanel3);

    jPanel4.setBackground(new java.awt.Color(211, 224, 234));
    jPanel4.setPreferredSize(new java.awt.Dimension(940, 508));

    jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(39, 102, 120));
    jLabel11.setText("Customers");

    jButton1.setBackground(new java.awt.Color(122, 178, 178));
    jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jButton1.setForeground(new java.awt.Color(39, 102, 120));
    jButton1.setText("Delete");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setBackground(new java.awt.Color(122, 178, 178));
    jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(39, 102, 120));
    jButton2.setText("Edit");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    Table1.setBackground(new java.awt.Color(122, 178, 178));
    Table1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Name", "ID", "Room no", "Room Type", "Check-in", "Check-out", "RezervationType"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    Table1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            Table1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(Table1);

    jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(39, 102, 120));
    jLabel10.setText("Name");

    name1.setPreferredSize(new java.awt.Dimension(80, 25));

    jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(39, 102, 120));
    jLabel12.setText("ID");

    jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(39, 102, 120));
    jLabel13.setText("Room No");

    jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(39, 102, 120));
    jLabel14.setText("Room Type");

    jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(39, 102, 120));
    jLabel15.setText("Check-in");

    jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(39, 102, 120));
    jLabel16.setText("Check-out");

    IDd.setPreferredSize(new java.awt.Dimension(80, 25));
    IDd.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            IDdActionPerformed(evt);
        }
    });

    roomNo.setPreferredSize(new java.awt.Dimension(80, 25));

    jButton5.setBackground(new java.awt.Color(122, 178, 178));
    jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jButton5.setForeground(new java.awt.Color(39, 102, 120));
    jButton5.setText("Done");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    roomtype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single    => 100", "Double   => 200", "Triple   => 300",
        "Family   => 400", "Suit     => 500"}));

jButton6.setBackground(new java.awt.Color(122, 178, 178));
jButton6.setText("Servies");
jButton6.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton6ActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(46, 46, 46)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(check_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(roomtype1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(8, 8, 8))))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel11)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(52, 52, 52))))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(IDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(roomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(roomtype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(check_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton5))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel11)
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
            .addComponent(jButton6)
            .addGap(28, 28, 28))
    );

    jTabbedPane2.addTab("Customers", jPanel4);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String stuId = IDd.getText().trim();
        String stuName = name1.getText().trim();
        String roomno = roomNo.getText().trim();
        String toomtype1 = (String) roomtype1.getSelectedItem();

        // Here to get the date as string
        Date date = check_in.getDate();
        String checkindate;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        checkindate = sdf.format(date);

        date = check_out.getDate();
        String checkoutdate;
        sdf = new SimpleDateFormat("yyyy/MM/dd");
        checkoutdate = sdf.format(date);
        // The room number should be numbers just
        pattren = "^^[1-6][0-99]|[7][00]$";
        if (!roomNo.getText().matches(pattren)) {
            JOptionPane.showMessageDialog(this, "enter a valid room number");
            return;
        }
        try {
            prSt = dbhandler.getConnection().prepareStatement("UPDATE rezervations SET Name=?,Roomno=?,Roomtype=?,Check_in=?,Check_out=? WHERE IdCard =?;");
            prSt.setString(1, stuName);
            prSt.setString(2, roomno);
            prSt.setString(3, toomtype1);
            prSt.setString(4, checkindate);
            prSt.setString(5, checkoutdate);
            prSt.setString(6, stuId);

            prSt.executeUpdate();
            JOptionPane.showMessageDialog(this, "The customers updates ");
            getAllcustemrs();
            // Make the fields empty after Updating
            name1.setText("");
            IDd.setText("");
            roomNo.setText("");
            check_in.setDate(null);
            check_out.setDate(null);
            roomtype1.setSelectedIndex(0);
            setEnabled();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void IDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDdActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked

        int rowIndex = Table1.getSelectedRow();
        try {
            // when click on row It will set all the valus of fields
            name1.setText(Table1.getValueAt(rowIndex, 0).toString());
            name1.setEnabled(false);

            IDd.setText(Table1.getValueAt(rowIndex, 1).toString());
            IDd.setEnabled(false);

            roomNo.setText(Table1.getValueAt(rowIndex, 2).toString());
            roomNo.setEnabled(false);

            roomtype1.setSelectedItem(Table1.getValueAt(rowIndex, 3).toString());
            roomtype1.setEnabled(false);

            // This is for date 
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            Date parsedDate = sdf.parse(Table1.getValueAt(rowIndex, 4).toString());
            check_in.setDate(parsedDate);
            check_in.setEnabled(false);

            Date parsedDate2 = sdf.parse(Table1.getValueAt(rowIndex, 5).toString());
            check_out.setDate(parsedDate2);
            check_out.setEnabled(false);

        } catch (Exception e) {
        }


    }//GEN-LAST:event_Table1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        name1.setEnabled(true);

        IDd.setEnabled(false);

        roomNo.setEnabled(true);

        roomtype1.setEnabled(true);

        check_in.setEnabled(true);

        check_out.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rowIndex = Table1.getSelectedRow();
        String id = IDd.getText();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select row to delete");
            return;
        }

        int confirmDialog = JOptionPane.showConfirmDialog(null,
                "Are you sure you want delete this custemr?", "Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirmDialog == JOptionPane.YES_OPTION) {
            try {
                prSt = dbhandler.getConnection().prepareStatement("DELETE FROM rezervations WHERE IdCard=?");
                prSt.setString(1, id);
                prSt.executeUpdate();

                getAllcustemrs();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            return;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (name.getText().isEmpty() || id.getText().isEmpty() || roomno.getText().isEmpty() || checkin.getDateFormatString().isEmpty() || checkout.getDateFormatString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields");
            return;
        }
        // The Id should be minimum 8 digit
        pattren = "^\\d{8,}$";
        if (!id.getText().matches(pattren)) {
            JOptionPane.showMessageDialog(this, "enter a valid ID with minimum 8 Digit");
            return;
        }
        // The room number should be numbers just
        pattren = "^^[1-6][0-99]|[7][00]$";
        if (!roomno.getText().matches(pattren)) {
            JOptionPane.showMessageDialog(this, "enter a valid room number");
            return;
        }
        // Check if the room selected before
        try {
            statement = dbhandler.getConnection().createStatement();
            result = statement.executeQuery("SELECT * FROM rezervations WHERE Roomno='" + roomno.getText() + "'");
            if (result.next()) {
                JOptionPane.showMessageDialog(this, "This room not avaliable now !");
                return;
            }

        } catch (Exception e) {

        }

        // Check if the checkin after checkout
        Date date1 = checkin.getDate();
        Date date2 = checkout.getDate();
        if (date1 != null && date2 != null) { // Check if both dates are selected
            if (date2.compareTo(date1) < 0) {
                JOptionPane.showMessageDialog(this, "Check in must be bofore Check out");
                return;
            }
        }

        // Now adding the custemer booking to database
        try {
            Date date = checkin.getDate();
            String checkindate;
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            checkindate = sdf.format(date);

            date = checkin.getDate();
            String checkoutdate;
            sdf = new SimpleDateFormat("yyyy/MM/dd");
            checkoutdate = sdf.format(date);
            // Prepare the SQL statement
            prSt = dbhandler.getConnection().prepareStatement(
                    "INSERT INTO rezervations (Name, IdCard, Roomno, Roomtype, Check_in, Check_out, RezerType) VALUES (?, ?, ?, ?, ?, ?,?)");
            prSt.setString(1, name.getText());
            prSt.setString(2, id.getText());
            prSt.setString(3, roomno.getText());
            prSt.setString(4, roomtype.getSelectedItem().toString());
            prSt.setString(5, checkindate);
            prSt.setString(6, checkoutdate);
            prSt.setString(7, "offline");
            // Execute the statement
            prSt.executeUpdate();

            // insert into customers
            prSt = dbhandler.getConnection().prepareStatement(
                    "INSERT INTO customers (Name, IdCard) VALUES (?, ?)");
            prSt.setString(1, name.getText());
            prSt.setString(2, id.getText());
            // Execute the statement
            prSt.executeUpdate();
            //

            JOptionPane.showMessageDialog(this, "Done!, your rezervation successfully Done");
            getAllcustemrs();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "This Id not abalable now (Used before)", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Welcome w = new Welcome();
        w.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        Servies s = new Servies();
        s.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDd;
    private javax.swing.JTable Table1;
    private com.toedter.calendar.JDateChooser check_in;
    private com.toedter.calendar.JDateChooser check_out;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField roomNo;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JComboBox<String> roomtype1;
    // End of variables declaration//GEN-END:variables
}
